version: '2'


networks:
  proxy:
    external: true

services:

  hello-rest-h2:
    image: uportal/demo-initial:latest
    labels:
      - "traefik.backend=demo-initial-h2"
      - "traefik.frontend.rule=Host:demo-initial-h2.united-portal.com"
      - "traefik.docker.network=proxy"
      - "traefik.port=8080"
      - "traefik.enable=true"
    expose:
      - 8080
    restart: always
    networks:
      - proxy
    environment:
      APP_NAME: Demo Initial with H2
      ACTIVE_PROFILES: dev,h2
