version: '3'


networks:
  proxy:
    external: true

services:

  demoinitial:
    image: sn0wcr33per/demo-initial:latest
    labels:
      - "traefik.http.routers.ticketsystem.rule=Host(`${DEMO_INITIAL_URL}`)"
      - "traefik.http.routers.ticketsystem.tls=true"
      - "traefik.http.routers.ticketsystem.tls.certresolver=lets-encrypt"
      - "traefik.port=8080"
    restart: always
    networks:
      - proxy
    expose:
      - 8080
    environment:
      APP_NAME: Demo Initial with Spring Boot and H2
      ACTIVE_PROFILES: dev,h2
      APP_URL: "https://${DEMO_INITIAL_URL}"
    container_name: ticketsystem
